import {ItemData} from '../models/itemList';

export const Lists: ItemData[] = [
  {
    id: 1,
    name: 'મંડપ',
    vidhi_things: {
      manek: 'માણેક સ્તંભ',
      mindhol: 'મીંઢોળ',
      vashaSoti: 'વાંસની સોટી',
      kundu: 'કુંડુ',
      lalCloth: 'લાલ પીસ',
      ghau: 'ઘઉં',
      chokhha: 'ચોખા',
      mag: 'મગ',
      shriFal: 'શ્રી ફલ',
      sopari: 'સોપારી',
      sukomevo: 'સૂકો મેવો',
      sakar: 'સાકર',
      goldhana: 'ગોળધાણા',
      abil: 'અબીલ ',
      gulal: 'ગુલાલ',
      kanku: 'કંકુ',
      nadachhadi: 'નાડાછડી',
      sutardadi: 'સુતર દોરી',
      agarbati: 'અગરબત્તી',
      bakas: 'બાકસ',
      bajot: 'બાજોટ',
      patalo: 'પાટલો',
      thali: 'થાળી',
      vataka: 'વાટકા',
      chamchi: 'ચમચી',
      trambanokalash: 'તાંબા નો કલશ',
      fulhar: 'ફુલહાર',
      fulchhutta: 'ફુલછુટા',
      asopalavtoran: 'આસોપાલવ તોરણ',
      nagarvelpan: 'નાગરવેલ પાન',
    },
  },
  {
    id: 2,
    name: 'લગ્ન',
    vidhi_things: {
      mindhol: 'મીંઢોળ',
      manek: 'માણેક સ્તંભ',
      vashaSoti: 'વાસ સોટી',
      shriFal: 'શ્રી ફલ',
      lalCloth: 'લાલ પીસ',
      ghau: 'ઘઉં',
    },
  },
];

export const vidhiThingsUseAll = {
  panchamrut: 'પંચામૃત',
  pani: 'પાણી',
  aasan: 'આસન',
  nepkin: 'નેપકિન',
  chhedachhedi: 'છેડાછેડી',
  ganeshnimatali: 'ગણેશની માટલી',
};
