import {ItemData} from '../models/itemList';

export const Lists: ItemData[] = [
  {
    id: 1,
    name: 'મંડપ',
    vidhi_things: {
      manek: 'માણેક સ્તંભ',
      mindhol: 'મીંઢોળ',
      vashaSoti: 'વાંસની સોટી',
      kundu: 'કુંડુ',
      lalCloth: 'લાલ પીસ',
      ghau: 'ઘઉં',
      chokhha: 'ચોખા',
      mag: 'મગ',
      shriFal: 'શ્રી ફલ',
      sopari: 'સોપારી',
      sukomevo: 'સૂકો મેવો',
      sakar: 'સાકર',
      goldhana: 'ગોળધાણા',
      abil: 'અબીલ ',
      gulal: 'ગુલાલ',
      kanku: 'કંકુ',
      nadachhadi: 'નાડાછડી',
      sutardadi: 'સુતર દોરી',
      agarbati: 'અગરબત્તી',
      bakas: 'બાકસ',
      bajot: 'બાજોટ',
      patalo: 'પાટલો',
      thali: 'થાળી',
      vataka: 'વાટકા',
      chamchi: 'ચમચી',
      trambanokalash: 'ત્રાંબા નો કલશ',
      fulhar: 'ફુલહાર',
      fulchhutta: 'ફુલછુટા',
      asopalavtoran: 'આસોપાલવ તોરણ',
      nagarvelpan: 'નાગરવેલ પાન',
      ganeshnimatali: 'ગણેશની માટલી',
    },
  },
  {
    id: 2,
    name: 'લગ્ન',
    vidhi_things: {
      ghau: 'ઘઉં',
      chokhha: 'ચોખા',
      mag: 'મગ',
      shriFal: 'શ્રી ફલ',
      sopari: 'સોપારી',
      javtal: 'જવતલ',
      ghee: 'ઘી',
      supadu: 'સૂપડું',
      samputjodi: 'સંપુટ ની જોડી',
      idniyapindiya: 'ઇડીંયા પિંડિયા',
      kansarvasan: 'કંસાર ના વસન',
      kansar: 'કંસાર',
      lalCloth: 'લાલ પીસ',
      whitecloth: 'સફેદ પીસ',
      chhana: 'છાણા ',
      bakas: 'બાકસ',
      kapurgoti: 'કપૂર ની ગોટી',
      bajot: 'બાજોટ',
      patalo: 'પાટલો',
      thali: 'થાળી',
      vataka: 'વાટકા',
      chamchi: 'ચમચી',
      trambanokalash: 'ત્રાંબા નો કલશ',
      saamaiyu: 'સામૈયુ',
      fulhar: 'ફુલહાર',
      fulchhutta: 'ફુલછુટા',
      asopalavtoran: 'આસોપાલવ તોરણ',
      nagarvelpan: 'નાગરવેલ પાન',
      havankund: 'હવન કુંડ',
      ganeshnimatali: 'ગણેશની માટલી',
    },
  },
  
];

export const vidhiThingsUseAll = {
  panchamrut: 'પંચામૃત',
  pani: 'પાણી',
  aasan: 'આસન',
  nepkin: 'નેપકિન',
  chhedachhedi: 'છેડાછેડી',
};
